# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{graphiterb}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip (flip) Kromer (@mrflip)"]
  s.date = %q{2010-08-16}
  s.description = %q{Uses http://github.com/mrflip/configliere and http://graphite.wikidot.com}
  s.email = %q{info@infochimps.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "examples/api_call_monitor.rb",
     "examples/file_monitor.rb",
     "examples/loadavg_graphite_sender.rb",
     "examples/run_servers.sh",
     "examples/storage_monitor.rb",
     "examples/toy.rb",
     "graphiterb.gemspec",
     "lib/graphiterb.rb",
     "lib/graphiterb/graphite_logger.rb",
     "lib/graphiterb/graphite_script.rb",
     "lib/graphiterb/graphite_sender.rb",
     "lib/graphiterb/graphite_system_logger.rb",
     "spec/graphiterb_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/infochimps/graphiterb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fast Ubiquitous Dashboard Logs with Graphite (http://graphite.wikidot.com)}
  s.test_files = [
    "spec/graphiterb_spec.rb",
     "spec/spec_helper.rb",
     "examples/storage_monitor.rb",
     "examples/api_call_monitor.rb",
     "examples/loadavg_graphite_sender.rb",
     "examples/toy.rb",
     "examples/file_monitor.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

